import type { CheckResult } from './types';

export function renderReport(results: CheckResult[], meta: { startedAt: string; finishedAt: string; runNumber: number }): string {
  const passCount = results.filter((r) => r.pass).length;
  const lines: string[] = [];

  lines.push('# ACCEPTANCE.md');
  lines.push('');
  lines.push('Generated by [`acceptance/run-acceptance.ts`](./run-acceptance.ts) against the local Docker Compose stack');
  lines.push('(`docker-compose.yml` + `docker-compose.test.yml` + `acceptance/docker-compose.acceptance.yml` +');
  lines.push('`docker-compose.observability.yml` under the `observability` profile). Executes the six acceptance');
  lines.push('criteria from [`../../ARCHITECTURE.md`](../../ARCHITECTURE.md) end-to-end — no mocks, no simulated results.');
  lines.push('');
  lines.push(`**Run ${meta.runNumber}** — started ${meta.startedAt}, finished ${meta.finishedAt}`);
  lines.push('');
  lines.push(`## Result: ${passCount}/6 PASS`);
  lines.push('');
  lines.push('| # | Criterion | Result | Duration |');
  lines.push('|---|---|---|---|');
  results.forEach((r, i) => {
    const badge = r.pass ? '✅ PASS' : '❌ FAIL';
    lines.push(`| ${i + 1} | ${r.title} | ${badge} | ${(r.durationMs / 1000).toFixed(1)}s |`);
  });
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const [i, r] of results.entries()) {
    lines.push(`## ${i + 1}. ${r.title}`);
    lines.push('');
    lines.push(`**Criterion (ARCHITECTURE.md):** ${r.criterion}`);
    lines.push('');
    lines.push(`**Result:** ${r.pass ? '✅ PASS' : '❌ FAIL'}  `);
    lines.push(`**Summary:** ${r.summary}  `);
    lines.push(`**Duration:** ${(r.durationMs / 1000).toFixed(1)}s (${r.startedAt} → ${r.finishedAt})`);
    lines.push('');
    if (r.error) {
      lines.push(`**Error:** ${r.error}`);
      lines.push('');
    }
    for (const block of r.evidence) {
      lines.push(`<details><summary>${block.label}</summary>`);
      lines.push('');
      lines.push('```' + (block.lang ?? 'text'));
      lines.push(block.content);
      lines.push('```');
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}
